" 基本設定
source ~/.vim/rc.d/basic.vimrc
" vundle.vim
source ~/.vim/rc.d/bundle.vimrc
" ステータスバー
source ~/.vim/rc.d/statusline.vimrc
" 表示設定
source ~/.vim/rc.d/apperance.vimrc
" エンコーディング
source ~/.vim/rc.d/encoding.vimrc
" インデント
source ~/.vim/rc.d/indent.vimrc
" 補完
source ~/.vim/rc.d/completion.vimrc
" 検索
source ~/.vim/rc.d/search.vimrc
" 移動
source ~/.vim/rc.d/moving.vimrc
" 編集
source ~/.vim/rc.d/editing.vimrc
